
# tap repositories and their packages

tap 'homebrew/core'
brew 'aircrack-ng'
brew 'aom'
brew 'apr'
brew 'apr-util'
brew 'autoconf'
brew 'automake'
brew 'autopano-sift-c'
brew 'aws-elasticbeanstalk'
brew 'aws-iam-authenticator'
brew 'awscli'
brew 'bash-completion'
brew 'bison'
brew 'cabal-install'
brew 'carthage'
brew 'ceres-solver'
brew 'circleci'
brew 'cmake'
brew 'coreutils'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'doxygen'
brew 'elixir'
brew 'erlang'
brew 'exiftool'
brew 'fabric'
brew 'ffmpeg'
brew 'flac'
brew 'gawk'
brew 'gcc'
brew 'gdb'
brew 'gettext'
brew 'ghc'
brew 'git-flow'
brew 'git-lfs'
brew 'gitlab-runner'
brew 'glib'
brew 'gnu-getopt'
brew 'gnu-prolog'
brew 'gnu-sed'
brew 'gnuplot'
brew 'gperf'
brew 'gperftools'
brew 'gradle'
brew 'grails'
brew 'graphviz'
brew 'grpcurl'
brew 'gtk+'
brew 'harfbuzz'
brew 'haskell-stack'
brew 'helm'
brew 'help2man'
brew 'hicolor-icon-theme'
brew 'htop'
brew 'httpd'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'imagemagick@6'
brew 'jq'
brew 'kubernetes-cli'
brew 'libass'
brew 'libcroco'
brew 'libdnet'
brew 'libdvdcss'
brew 'libiconv'
brew 'libmagic'
brew 'libpano'
brew 'libpcap'
brew 'libtool'
brew 'libunwind-headers'
brew 'libwebsockets'
brew 'libxml2'
brew 'libxslt'
brew 'luarocks'
brew 'm4'
brew 'mackup'
brew 'make'
brew 'mas'
brew 'maven'
brew 'mecab'
brew 'mecab-ipadic'
brew 'mysql'
brew 'mysql@5.6'
brew 'ncurses'
brew 'neon'
brew 'ninja'
brew 'nkf'
brew 'nmap'
brew 'nodeenv'
brew 'numpy'
brew 'oniguruma'
brew 'opencv'
brew 'openjdk'
brew 'openjdk@11'
brew 'openssl@1.1'
brew 'ossp-uuid'
brew 'p7zip'
brew 'pandoc'
brew 'pango'
brew 'peco'
brew 'pkg-config'
brew 'portaudio'
brew 'postgresql'
brew 'postgresql@10'
brew 'postgresql@11'
brew 'pstree'
brew 'pyenv'
brew 'pyqt'
brew 'qt'
brew 'rbenv'
brew 'readline'
brew 'redis'
brew 'rsync'
brew 'ruby-build'
brew 'scala'
brew 'shared-mime-info'
brew 'sox'
brew 'speedtest-cli'
brew 'sphinx-doc'
brew 'swiftlint'
brew 'swig'
brew 'telnet'
brew 'terminal-notifier'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'v8'
brew 'v8@3.15'
brew 'w3m'
brew 'watch'
brew 'watsonbox/cmu-sphinx/cmu-pocketsphinx', args: ['HEAD']
brew 'watsonbox/cmu-sphinx/cmu-sphinxbase', args: ['HEAD']
brew 'weaveworks/tap/eksctl'
brew 'wget'
brew 'yajl'
brew 'yarn'
brew 'youtube-dl'
brew 'zlib'
brew 'zsync'

tap 'homebrew/bundle'

tap 'homebrew/cask-versions'

tap 'homebrew/services'

tap 'homebrew/cask'
cask 'amazon-music'
cask 'android-studio'
cask 'appcleaner'
cask 'arduino'
cask 'atom'
cask 'bitbar'
cask 'brave-browser'
cask 'calibre'
cask 'clipy'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'geekbench'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-japanese-ime'
cask 'graphql-playground'
cask 'gyazo'
cask 'handbrake'
cask 'intellij-idea'
cask 'iterm2'
cask 'lastfm'
cask 'libreoffice'
cask 'little-snitch'
cask 'miniconda'
cask 'monolingual'
cask 'ngrok'
cask 'osxfuse'
cask 'phantomjs'
cask 'reveal'
cask 'shadowsocksx-ng'
cask 'snes9x'
cask 'sublime-text'
cask 'supercollider'
cask 'telegram-desktop'
cask 'thunderbird'
cask 'tor-browser'
cask 'v2rayx'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'wireshark'
cask 'xquartz'
cask 'zoomus'

tap 'chef/chef'
cask 'chefdk'

tap 'datawire/blackbird'
brew 'datawire/blackbird/telepresence'

tap 'ethereum/ethereum'

tap 'heroku/brew'
brew 'heroku/brew/heroku'

tap 'mongodb/brew'
brew 'mongodb/brew/mongodb-community-shell'
brew 'mongodb/brew/mongodb-community@3.4'

tap 'petere/postgresql'

tap 'pivotal/tap'
brew 'pivotal/tap/springboot'

tap 'rcmdnk/file'
brew 'rcmdnk/file/brew-file'

tap 'v2ray/v2ray'
brew 'v2ray/v2ray/v2ray-core'

tap 'watsonbox/cmu-sphinx'

tap 'weaveworks/tap'

# App Store applications
mas '1Blocker', id: 1107421413
mas 'AdBlock', id: 1402042596
mas 'AdGuard', id: 1440147259
mas 'DevCleaner', id: 1388020431
mas 'ForkLift', id: 412448059
mas 'GarageBand', id: 682658836
mas 'Ghostery', id: 1436953057
mas 'iCompta', id: 1149778308
mas 'iMovie', id: 408981434
mas 'Keeper', id: 414781829
mas 'Keynote', id: 409183694
mas 'Kindle', id: 405399194
mas 'LINE', id: 539883307
mas 'Notability', id: 736189492
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Pocket', id: 568494494
mas 'QQ', id: 451108668
mas 'QQMusic', id: 595615424
mas 'Save to Pocket', id: 1477385213
mas 'Slack', id: 803453959
mas 'WeChat', id: 836500024
mas 'Xcode', id: 497799835
